formacao = input('Digite a formação do seu time:')
jogadores = input('Digite os jogadores do seu time:')
coach = input('Digite o técnico da sua equipe: ')
time = jogadores.split()
if formacao == "4-4-2":
  print()
  print(time[0].center(35))
  print()
  print()
  print(time[1].center(5), time[2].center(9), time[3].center(9), time[4].center(7))
  print()
  print()
  print(time[5].center(20), time[6])
  print()
  print()
  print(time[7].center(13), time[8].center(30))
  print()
  print()
  print(time[9].center(20), time[10].center(10))
  print()
  print()
  print("Téc.: ", coach)
elif formacao == "4-3-3":
  print()
  print(time[0].center(35))
  print()
  print()
  print(time[1].center(5), time[2].center(9), time[3].center(9), time[4].center(7))
  print()
  print()
  print(time[5].center(13), time[6], time[7].center(5))
  print()
  print()
  print(time[8].center(10), time[9].center(13), time[10].center(11))
  print()
  print()
  print("Téc.: ", coach)